spring:
  datasource:
    url: jdbc:oracle:thin:@172.20.10.65:1521:CGEN
    username: ADMNFRM
    password: ADMNFRM
  jpa:
    hibernate:
      ddl-auto: update
      database: oracle
eurek:
  client:
    enabled: false
server:
  error:
    include-message: always