# This is a sample command please replace with correct command
spring:
  application:
    name: coop-system

eurek:
  client:
    enabled: false
server:
  port: 54571

  spring:
    servlet:
      multipart:
        enabled: true

#1999-11-27 ISO8601
#--spring.profiles.active=dev --eureka.instance.preferIpAddress=true --eureka.client.serviceUrl.defaultZone=http://172.20.10.173:8761/eureka

