spring:
  datasource:
    url: jdbc:postgresql://172.21.112.134:5432/CGEN_LIVE
    username: postgres
    password: freaks
    hikari:
      schema: ADMINFRM

  jpa:
    hibernate:
      ddl-auto: update

eurek:
  client:
    enabled: false

server:
  port: 54571

