# This is a sample command please replace with correct command
spring:
  datasource:
    url: jdbc:postgresql://172.20.11.164:5432/cgen_live
    username: postgres
    password: cgen@#pg2021
    hikari:
      schema: dbkanrich

  jpa:
    hibernate:
      ddl-auto: update
eurek:
  client:
    enabled: false

jwt:
  token:
    validity: 18000
    prefix: Bearer
  signing:
    key: signingkey
  authorities:
    key: roles
  header:
    string: Authorization

server:
  port: 54000